### ISSUE TITLE
AssertionError: detectron ops lib not found

### ISSUE THREAD

**Issue by Vuurtoren2000** [facebookresearch/DensePose#133]
Hi all,

I run the following configuration:

    Operating system: Ubuntu 16.04
    Compiler version: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)
    CUDA version: 9.0
    cuDNN version: 7.3.0
    NVIDIA driver version:
    GPU models (for all devices if they are not all the same): 2x Tesla V100
    python --version output: 2.7.12

I get the following error when I try this command.

Command:
python2 $DENSEPOSE/detectron/tests/test_spatial_narrow_as_op.py

Error:
Traceback (most recent call last):
File "detectron/tests/test_spatial_narrow_as_op.py", line 80, in <module>
   c2_utils.import_detectron_ops()
File "/home/cp/DensePose/detectron/utils/c2.py", line 33, in import_detectron_ops
   detectron_ops_lib = envu.get_detectron_ops_lib()
File "/home/cp/DensePose/detectron/utils/env.py", line 63, in get_detectron_ops_lib
   ('Detectron ops lib not found; make sure that your Caffe2 '
AssertionError: Detectron ops lib not found; make sure that your Caffe2 version includes Detectron module

Hope you can help!

**Comment by jaggernaut007** [comment]
Run the detectron setup. I should work.

**Comment by Vuurtoren2000** [comment]
Hello jaggernaut. I ofcourse ran the setup and it was completed without errors.

**Comment by ingramator** [comment]
Did you compile from source or use an anaconda package for caffe2? I know older versions of the anaconda package were not compiled with detectron modules and Im not sure if they have updated it since. I'm going to hazard a guess that you did use anaconda in which case you 100% should be compiling from source, or use the docker image. If you compiled from source make sure you are on a recent version of the caffe2/pytorch library and you didnt checkout a much older commit or modify your cmakelist

**Comment by Vuurtoren2000** [comment]
Thanks ingramator for your help. I compiled from source. I don't use anaconda but pip. I got caffe2 running and caffe2 detects the correct number of GPUs in my system. I followed the installation steps on this link: https://github.com/facebookresearch/DensePose/blob/master/INSTALL.md.

**Comment by ingramator** [comment]
This is the best guide for compiling caffe2 from source: https://tech.amikelive.com/node-706/comprehensive-guide-installing-caffe2-with-gpu-support-by-building-from-source-on-ubuntu-16-04/

**Comment by twkillian** [comment]
@Vuurtoren2000 I'm having this same issue and followed the same procedure as you had in your original post.

Were you able to solve your issue? If so, how?

**Comment by twkillian** [comment]
@michael230779 and others... I solved this issue by compiling the detectron repo following the installation instructions for the Detectron library found [here](https://github.com/facebookresearch/Detectron/blob/master/INSTALL.md):

After getting that compiled, the test script: 
`python2 $DENSEPOSE/detectron/tests/test_spatial_narrow_as_op.py`

ran as expected.

**Comment by michael230779** [comment]
Thanks @twkillian. I removed the detectron repository that I cloned as part of the densepose repository and replaced it with the original detectron repository from the respective github repo. Works just fine now. Still wondering what's missing in the densepose/detectron repository, though...

**Comment by robpieke** [comment]
Going off your comment of "using the detectron repo, everything works", I think the meaningful difference is this:
https://github.com/facebookresearch/Detectron/blob/master/detectron/utils/env.py#L67
Whereby detectron searches `torch/lib/` (and `lib/`) and densepose only searches `lib/`

**Comment by life-efficient** [comment]
If you're following this guide (https://github.com/Johnqczhang/densepose_installation) use his forked repo
