### ISSUE TITLE
out of memoryError from operator

### ISSUE THREAD

**Issue by liangwx** [facebookresearch/DensePose#139]
Thanks for sharing your great works. With [the installation of densepose](https://github.com/facebookresearch/DensePose/blob/master/INSTALL.md) completed, I went to "[Testing with Pretrained Models](https://github.com/facebookresearch/DensePose/blob/master/GETTING_STARTED.md#testing-with-pretrained-models)", shell lines was as follows:
`python2 tools/test_net.py \
    --cfg configs/DensePose_ResNet101_FPN_s1x-e2e.yaml \
    TEST.WEIGHTS https://s3.amazonaws.com/densepose/DensePose_ResNet101_FPN_s1x-e2e.pkl \
    NUM_GPUS 1`

After  the lines above,I got error as follows:

> loading annotations into memory...
Done (t=0.68s)
creating index...
index created!
loading annotations into memory...
Done (t=0.68s)
creating index...
index created!
WARNING cnn.py:  25: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
INFO net.py:  51: Loading weights from: /tmp/detectron-download-cache/DensePose_ResNet101_FPN_s1x-e2e.pkl
[I net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 0.000109697 secs
[I net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 9.3511e-05 secs
[I net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 1.2213e-05 secs
[I net_async_base.h:198] Using specified CPU pool size: 4; NUMA node id: -1
[I net_async_base.h:203] Created new CPU pool, size: 4; NUMA node id: -1
[I net_async_base.h:198] Using specified CPU pool size: 4; NUMA node id: -1
[I net_async_base.h:203] Created new CPU pool, size: 4; NUMA node id: -1
INFO test_engine.py: 292: im_detect: range [1, 1508] of 1508: 1/1508 0.987s + 0.000s (eta: 0:24:47)
INFO test_engine.py: 292: im_detect: range [1, 1508] of 1508: 11/1508 0.537s + 0.000s (eta: 0:13:23)
INFO test_engine.py: 292: im_detect: range [1, 1508] of 1508: 21/1508 0.514s + 0.000s (eta: 0:12:44)
INFO test_engine.py: 292: im_detect: range [1, 1508] of 1508: 31/1508 0.500s + 0.000s (eta: 0:12:18)
INFO test_engine.py: 292: im_detect: range [1, 1508] of 1508: 41/1508 0.489s + 0.000s (eta: 0:11:57)
INFO test_engine.py: 292: im_detect: range [1, 1508] of 1508: 51/1508 0.484s + 0.000s (eta: 0:11:44)
INFO test_engine.py: 292: im_detect: range [1, 1508] of 1508: 61/1508 0.478s + 0.000s (eta: 0:11:31)
INFO test_engine.py: 292: im_detect: range [1, 1508] of 1508: 71/1508 0.472s + 0.000s (eta: 0:11:18)
INFO test_engine.py: 292: im_detect: range [1, 1508] of 1508: 81/1508 0.469s + 0.000s (eta: 0:11:09)
INFO test_engine.py: 292: im_detect: range [1, 1508] of 1508: 91/1508 0.464s + 0.000s (eta: 0:10:58)
INFO test_engine.py: 292: im_detect: range [1, 1508] of 1508: 101/1508 0.460s + 0.000s (eta: 0:10:47)
INFO test_engine.py: 292: im_detect: range [1, 1508] of 1508: 111/1508 0.462s + 0.000s (eta: 0:10:45)
INFO test_engine.py: 292: im_detect: range [1, 1508] of 1508: 121/1508 0.458s + 0.000s (eta: 0:10:35)
INFO test_engine.py: 292: im_detect: range [1, 1508] of 1508: 131/1508 0.455s + 0.000s (eta: 0:10:26)
[E net_async_base.cc:422] [enforce fail at context_gpu.cu:342] error == cudaSuccess. 2 vs 0. Error at: /home/liangu/pytorch/caffe2/core/context_gpu.cu:342: out of memoryError from operator: 
input: "gpu_0/res4_12_branch2b" input: "gpu_0/res4_12_branch2c_w" output: "gpu_0/res4_12_branch2c" name: "" type: "Conv" arg { name: "kernel" i: 1 } arg { name: "exhaustive_search" i: 0 } arg { name: "stride" i: 1 } arg { name: "pad" i: 0 } arg { name: "order" s: "NCHW" } arg { name: "dilation" i: 1 } device_option { device_type: 1 device_id: 0 } engine: "CUDNN",  op Conv
WARNING workspace.py: 187: Original python traceback for operator `207` in network `generalized_rcnn` in exception above (most recent call last):
WARNING workspace.py: 192:   File "tools/test_net.py", line 111, in <module>
WARNING workspace.py: 192:   File "/home/liangu/densepose/densepose/detectron/core/test_engine.py", line 120, in run_inference
WARNING workspace.py: 192:   File "/home/liangu/densepose/densepose/detectron/core/test_engine.py", line 100, in result_getter
WARNING workspace.py: 192:   File "/home/liangu/densepose/densepose/detectron/core/test_engine.py", line 153, in test_net_on_dataset
WARNING workspace.py: 192:   File "/home/liangu/densepose/densepose/detectron/core/test_engine.py", line 233, in test_net
WARNING workspace.py: 192:   File "/home/liangu/densepose/densepose/detectron/core/test_engine.py", line 334, in initialize_model_from_cfg
WARNING workspace.py: 192:   File "/home/liangu/densepose/densepose/detectron/modeling/model_builder.py", line 119, in create
WARNING workspace.py: 192:   File "/home/liangu/densepose/densepose/detectron/modeling/model_builder.py", line 84, in generalized_rcnn
WARNING workspace.py: 192:   File "/home/liangu/densepose/densepose/detectron/modeling/model_builder.py", line 233, in build_generic_detection_model
WARNING workspace.py: 192:   File "/home/liangu/densepose/densepose/detectron/modeling/optimizer.py", line 46, in build_data_parallel_model
WARNING workspace.py: 192:   File "/home/liangu/densepose/densepose/detectron/modeling/model_builder.py", line 165, in _single_gpu_build_func
WARNING workspace.py: 192:   File "/home/liangu/densepose/densepose/detectron/modeling/FPN.py", line 55, in add_fpn_ResNet101_conv5_body
WARNING workspace.py: 192:   File "/home/liangu/densepose/densepose/detectron/modeling/FPN.py", line 96, in add_fpn_onto_conv_body
WARNING workspace.py: 192:   File "/home/liangu/densepose/densepose/detectron/modeling/ResNet.py", line 40, in add_ResNet101_conv5_body
WARNING workspace.py: 192:   File "/home/liangu/densepose/densepose/detectron/modeling/ResNet.py", line 103, in add_ResNet_convX_body
WARNING workspace.py: 192:   File "/home/liangu/densepose/densepose/detectron/modeling/ResNet.py", line 77, in add_stage
WARNING workspace.py: 192:   File "/home/liangu/densepose/densepose/detectron/modeling/ResNet.py", line 174, in add_residual_block
WARNING workspace.py: 192:   File "/home/liangu/densepose/densepose/detectron/modeling/ResNet.py", line 322, in bottleneck_transformation
WARNING workspace.py: 192:   File "/home/liangu/densepose/densepose/detectron/modeling/detector.py", line 399, in ConvAffine
WARNING workspace.py: 192:   File "/home/liangu/anaconda2/lib/python2.7/site-packages/caffe2/python/cnn.py", line 97, in Conv
WARNING workspace.py: 192:   File "/home/liangu/anaconda2/lib/python2.7/site-packages/caffe2/python/brew.py", line 107, in scope_wrapper
WARNING workspace.py: 192:   File "/home/liangu/anaconda2/lib/python2.7/site-packages/caffe2/python/helpers/conv.py", line 186, in conv
WARNING workspace.py: 192:   File "/home/liangu/anaconda2/lib/python2.7/site-packages/caffe2/python/helpers/conv.py", line 139, in _ConvBase
Traceback (most recent call last):
  File "tools/test_net.py", line 111, in <module>
    check_expected_results=True,
  File "/home/liangu/densepose/densepose/detectron/core/test_engine.py", line 120, in run_inference
    all_results = result_getter()
  File "/home/liangu/densepose/densepose/detectron/core/test_engine.py", line 100, in result_getter
    multi_gpu=multi_gpu_testing
  File "/home/liangu/densepose/densepose/detectron/core/test_engine.py", line 153, in test_net_on_dataset
    weights_file, dataset_name, proposal_file, output_dir, gpu_id=gpu_id
  File "/home/liangu/densepose/densepose/detectron/core/test_engine.py", line 260, in test_net
    im_detect_all(model, im, box_proposals, timers)
  File "/home/liangu/densepose/densepose/detectron/core/test.py", line 58, in im_detect_all
    model, im, cfg.TEST.SCALE, cfg.TEST.MAX_SIZE, boxes=box_proposals
  File "/home/liangu/densepose/densepose/detectron/core/test.py", line 158, in im_detect_bbox
    workspace.RunNet(model.net.Proto().name)
  File "/home/liangu/anaconda2/lib/python2.7/site-packages/caffe2/python/workspace.py", line 219, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/home/liangu/anaconda2/lib/python2.7/site-packages/caffe2/python/workspace.py", line 180, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at context_gpu.cu:342] error == cudaSuccess. 2 vs 0. Error at: /home/liangu/pytorch/caffe2/core/context_gpu.cu:342: out of memoryError from operator: 
input: "gpu_0/res4_12_branch2b" input: "gpu_0/res4_12_branch2c_w" output: "gpu_0/res4_12_branch2c" name: "" type: "Conv" arg { name: "kernel" i: 1 } arg { name: "exhaustive_search" i: 0 } arg { name: "stride" i: 1 } arg { name: "pad" i: 0 } arg { name: "order" s: "NCHW" } arg { name: "dilation" i: 1 } device_option { device_type: 1 device_id: 0 } engine: "CUDNN"

> 

As was shown above, It worked well until "131/1508". I guess it failed because of the memory of my GPU(or CPU) had run out, but I am not sure, and don't know what to do about it . As I'm a novice and newcomer here, any information would be helpful～
or  if the default batchsize is 1? if not , then how can I set batchsize to 1?

**Comment by liangwx** [comment]
@ingramator Thank you for your help. I had made it successful in a environment with stronger GPU.
