### ISSUE TITLE
OSError: "undefined symbol" when running "test_zero_even_op.py"

### ISSUE THREAD

**Issue by wswdx** [facebookresearch/DensePose#143]
**Traceback of the error:**

Traceback (most recent call last):
  File "detectron/tests/test_zero_even_op.py", line 117, in <module>
    c2_utils.import_custom_ops()
  File "/data/weidx/densepose/detectron/utils/c2.py", line 40, in import_custom_ops
    dyndep.InitOpsLibrary(custom_ops_lib)
  File "/home/weidx/anaconda3/envs/caffe2/lib/python2.7/site-packages/caffe2/python/dyndep.py", line 35, in InitOpsLibrary
    _init_impl(name)
  File "/home/weidx/anaconda3/envs/caffe2/lib/python2.7/site-packages/caffe2/python/dyndep.py", line 48, in _init_impl
    ctypes.CDLL(path)
  File "/home/weidx/anaconda3/envs/caffe2/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
**OSError: /data/weidx/densepose/build/libcaffe2_detectron_custom_ops_gpu.so: undefined symbol: _ZN6google8protobuf8internal9ArenaImpl28AllocateAlignedAndAddCleanupEmPFvPvE**

**I've tried to reinstall protobuf from source and also tried the solution of #119 , both of them don't help. And my protobuf's version is 3.6.1 now, while my caffe2 is installed from Pytorch source code. 
Please help me out of this! Thanks in advance!**

**Comment by ZhiyLiu** [comment]
@wswdx Did you solve your problem?

**Comment by ckyleda** [comment]
I am also encountering this issue, is clearly a fatal flaw within the way this project is structured.

**Comment by wswdx** [comment]
> @wswdx Did you solve your problem?

Sorry that I haven't notice your comment for so long. I just ignore it because I found testing pose estimation didn't require making ops on my own. If you only wants to use the well trained model to detect pose, there is no need to pass this "test_zero_even_op.py".

**Comment by wswdx** [comment]
> I am also encountering this issue, is clearly a fatal flaw within the way this project is structured.

Yes, maybe. I think you can follow the writers' cuda setting(cuda 8.0 + cudnn 6.0.21) and rebuild, maybe it will work.

**Comment by ckyleda** [comment]
This doesn't look like a CUDA/cudnn issue - it's definitely seems like a protobuf issue, which is no real surprise considering the amount of problems protobuf's always cause!
