### ISSUE TITLE
How to solve the 'EOFError' problem about retrain densepose 

### ISSUE THREAD

**Issue by Easyfeng222** [facebookresearch/DensePose#161]
INFO train.py: 171: Loading dataset: ('dense_coco_2014_train', 'dense_coco_2014_valminusminival')
loading annotations into memory...
Done (t=11.17s)
creating index...
index created!
.INFO json_dataset.py: 299: Loading proposals from: /tmp/detectron-download-cache/DensePose-RPN-train_fpn_resnet50.pkl
Traceback (most recent call last):
  File "tools/train_net.py", line 119, in <module>
    main()
  File "tools/train_net.py", line 101, in main
    checkpoints = detectron.utils.train.train_model()
  File "/home/feng/densepose/detectron/utils/train.py", line 50, in train_model
    setup_model_for_training(model, weights_file, output_dir)
  File "/home/feng/densepose/detectron/utils/train.py", line 149, in setup_model_for_training
    add_model_training_inputs(model)
  File "/home/feng/densepose/detectron/utils/train.py", line 173, in add_model_training_inputs
    cfg.TRAIN.DATASETS, cfg.TRAIN.PROPOSAL_FILES
  File "/home/feng/densepose/detectron/datasets/roidb.py", line 53, in combined_roidb_for_training
    roidbs = [get_roidb(*args) for args in zip(dataset_names, proposal_files)]
  File "/home/feng/densepose/detectron/datasets/roidb.py", line 38, in get_roidb
    crowd_filter_thresh=cfg.TRAIN.CROWD_FILTER_THRESH
  File "/home/feng/densepose/detectron/datasets/json_dataset.py", line 110, in get_roidb
    crowd_filter_thresh
  File "/home/feng/densepose/detectron/datasets/json_dataset.py", line 301, in _add_proposals_from_file
    proposals = pickle.load(f)
EOFError

**Comment by torpor29** [comment]
Hi, I met the same problem, did you figure out how to solve it?

**Comment by pavithraezhil** [comment]
Hi, I still have the same problem even after changing the weights to ResNet50. Please let me know if there is a fix.

Thank you.
