### ISSUE TITLE
a problem when I run the infer_simple.py 

### ISSUE THREAD

**Issue by mine114** [facebookresearch/DensePose#216]
I run the infer_simple.py  to test whether the installtion of densepose is successful,  but have this problem .I don't know what's wrong.

python2 tools/infer_simple.py \
>     --cfg configs/DensePose_ResNet101_FPN_s1x-e2e.yaml \
>     --output-dir DensePoseData/infer_out/ \
>     --image-ext jpg \
>     --wts https://dl.fbaipublicfiles.com/densepose/DensePose_ResNet101_FPN_s1x-e2e.pkl \
>     DensePoseData/demo_data/demo_im.jpg

and this is the problem

[E init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
/home/mine/densepose/detectron/core/config.py:1163: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(cfg_to_load)
WARNING cnn.py:  25: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
INFO net.py:  51: Loading weights from: /tmp/detectron-download-cache/DensePose_ResNet101_FPN_s1x-e2e.pkl
Traceback (most recent call last):
  File "tools/infer_simple.py", line 140, in <module>
    main(args)
  File "tools/infer_simple.py", line 91, in main
    model = infer_engine.initialize_model_from_cfg(args.weights)
  File "/home/mine/densepose/detectron/core/test_engine.py", line 336, in initialize_model_from_cfg
    model, weights_file, gpu_id=gpu_id,
  File "/home/mine/densepose/detectron/utils/net.py", line 56, in initialize_gpu_from_weights_file
    saved_cfg = load_cfg(src_blobs['cfg'])
  File "/home/mine/densepose/detectron/core/config.py", line 1163, in load_cfg
    return yaml.load(cfg_to_load)
  File "/home/mine/.local/lib/python2.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/mine/.local/lib/python2.7/site-packages/yaml/constructor.py", line 45, in get_single_data
    return self.construct_document(node)
  File "/home/mine/.local/lib/python2.7/site-packages/yaml/constructor.py", line 49, in construct_document
    data = self.construct_object(node)
  File "/home/mine/.local/lib/python2.7/site-packages/yaml/constructor.py", line 96, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/home/mine/.local/lib/python2.7/site-packages/yaml/constructor.py", line 628, in construct_python_object_new
    return self.construct_python_object_apply(suffix, node, newobj=True)
  File "/home/mine/.local/lib/python2.7/site-packages/yaml/constructor.py", line 611, in construct_python_object_apply
    value = self.construct_mapping(node, deep=True)
  File "/home/mine/.local/lib/python2.7/site-packages/yaml/constructor.py", line 214, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/home/mine/.local/lib/python2.7/site-packages/yaml/constructor.py", line 139, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/mine/.local/lib/python2.7/site-packages/yaml/constructor.py", line 101, in construct_object
    for dummy in generator:
  File "/home/mine/.local/lib/python2.7/site-packages/yaml/constructor.py", line 404, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/mine/.local/lib/python2.7/site-packages/yaml/constructor.py", line 214, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/home/mine/.local/lib/python2.7/site-packages/yaml/constructor.py", line 139, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/mine/.local/lib/python2.7/site-packages/yaml/constructor.py", line 96, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/home/mine/.local/lib/python2.7/site-packages/yaml/constructor.py", line 617, in construct_python_object_apply
    instance = self.make_python_instance(suffix, node, args, kwds, newobj)
  File "/home/mine/.local/lib/python2.7/site-packages/yaml/constructor.py", line 558, in make_python_instance
    node.start_mark)
yaml.constructor.ConstructorError: while constructing a Python instance
expected a class, but found <type 'builtin_function_or_method'>
  in "<unicode string>", line 3, column 20:
      BBOX_XFORM_CLIP: !!python/object/apply:numpy.core ...

**Comment by mine114** [comment]
I solved this problem. I using PyYAMLversion 3.12 instead of 4.1. like #37

**Comment by Johnqczhang** [comment]
@mine114 This issue should be closed since the problem has been solved.

**Comment by AydarAkhmetzyanov** [comment]
> @mine114 This issue should be closed since the problem has been solved.

i dont think so, default docker installation fails. Better to fix it.

**Comment by Johnqczhang** [comment]
> > @mine114 This issue should be closed since the problem has been solved.
> 
> i dont think so, default docker installation fails. Better to fix it.

@AydarAkhmetzyanov If you see [`Dockerfile`](https://github.com/facebookresearch/DensePose/blob/master/docker/Dockerfile), you will find that `pyyaml` is installed by `pip` specified in [requirements.txt](https://github.com/facebookresearch/DensePose/blob/master/requirements.txt). So, try to change [`pyyaml>=3.12`](https://github.com/facebookresearch/DensePose/blob/master/requirements.txt#L2) to `pyyaml=3.12` and then reinstall this project in a docker.

**Comment by Tony1868388** [comment]
where is the  PyYAML path

**Comment by SuperMisswei** [comment]
hello，I met the same  question and my pyyaml==3.12 ,I don't know why.

**Comment by dmoore247** [comment]
uh, why are newer versions of pyyaml failing? my version is 5.1, my environment is refusing to uninstall pyyaml 5.1. Could there be a problem with the .yaml file?

```Installing collected packages: pyyaml
  Found existing installation: PyYAML 5.1
Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.```
