### ISSUE TITLE
UV_Processed.mat Missing 

### ISSUE THREAD

**Issue by rachit2403** [facebookresearch/DensePose#22]
Hello, 

I was trying to execute the DensePose algorithm and I got an error, could kindly look at it. 

I ran this, on docker after installation. 

`sudo nvidia-docker run --rm -it densepose:c2-cuda9-cudnn7 python2 tools/infer_simple.py     --cfg configs/DensePose_ResNet101_FPN_s1x-e2e.yaml     --output-dir DensePoseData/infer_out/     --image-ext jpg     --wts https://s3.amazonaws.com/densepose/DensePose_ResNet101_FPN_s1x-e2e.pkl     DensePoseData/demo_data/demo_im.jpg`

And I am getting the following error, Also I don't see the UV_Processed.mat in the folder. 

`Traceback (most recent call last):
  File "tools/infer_simple.py", line 34, in <module>
    import detectron.core.test_engine as infer_engine
  File "/densepose/detectron/core/test_engine.py", line 27, in <module>
    from detectron.core.rpn_generator import generate_rpn_on_dataset
  File "/densepose/detectron/core/rpn_generator.py", line 36, in <module>
    from detectron.modeling import model_builder
  File "/densepose/detectron/modeling/model_builder.py", line 38, in <module>
    from detectron.modeling.detector import DetectionModelHelper
  File "/densepose/detectron/modeling/detector.py", line 25, in <module>
    from detectron.ops.collect_and_distribute_fpn_rpn_proposals \
  File "/densepose/detectron/ops/collect_and_distribute_fpn_rpn_proposals.py", line 19, in <module>
    import detectron.roi_data.fast_rcnn as fast_rcnn_roi_data
  File "/densepose/detectron/roi_data/fast_rcnn.py", line 26, in <module>
    import detectron.roi_data.body_uv_rcnn as body_uv_rcnn_roi_data
  File "/densepose/detectron/roi_data/body_uv_rcnn.py", line 32, in <module>
    DP = dp_utils.DensePoseMethods()
  File "/densepose/detectron/utils/densepose_methods.py", line 18, in __init__
    ALP_UV = loadmat( os.path.join(os.path.dirname(__file__), '../../DensePoseData/UV_data/UV_Processed.mat')  )
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 135, in loadmat
    MR = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 58, in mat_reader_factory
    byte_stream = _open_file(file_name, appendmat)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 23, in _open_file
    return open(file_like, 'rb')
IOError: [Errno 2] No such file or directory: '/densepose/detectron/utils/../../DensePoseData/UV_data/UV_Processed.mat'
`

Thank you in advance! It's a very interesting project

**Comment by vkhalidov** [comment]
Please be sure to perform steps described in the [Fetch DensePose data](https://github.com/facebookresearch/DensePose/blob/master/INSTALL.md#fetch-densepose-data) section and verify that the shell scripts execute properly. In particular, `get_densepose_uv.sh` should create `UV_data` directory and populate extract `UV_Processed.mat` into it.

**Comment by rachit2403** [comment]
Hello, 

Thank you for your reply, do we have to run the "setting up the coco dataset" also?

**Comment by rachit2403** [comment]
I did that, and reinstalled it again,

`rsaluja@bleen:~/densepose/DensePoseData$ cd ..

rsaluja@bleen:~/densepose$ cd DensePoseData/UV_data/

rsaluja@bleen:~/densepose/DensePoseData/UV_data$ ls

UV_Processed.mat  UV_symmetry_transforms.mat`

And the error persists,

`rsaluja@bleen:~/densepose/DensePoseData/UV_data$ sudo nvidia-docker run --rm -it densepose:c2-cuda9-cudnn7 python2 tools/infer_simple.py     --cfg configs/DensePose_ResNet101_FPN_s1x-e2e.yaml     --output-dir DensePoseData/infer_out/     --image-ext jpg     --wts https://s3.amazonaws.com/densepose/DensePose_ResNet101_FPN_s1x-e2e.pkl     DensePoseData/demo_data/demo_im.jpg
Traceback (most recent call last):
  File "tools/infer_simple.py", line 34, in <module>
    import detectron.core.test_engine as infer_engine
  File "/densepose/detectron/core/test_engine.py", line 27, in <module>
    from detectron.core.rpn_generator import generate_rpn_on_dataset
  File "/densepose/detectron/core/rpn_generator.py", line 36, in <module>
    from detectron.modeling import model_builder
  File "/densepose/detectron/modeling/model_builder.py", line 38, in <module>
    from detectron.modeling.detector import DetectionModelHelper
  File "/densepose/detectron/modeling/detector.py", line 25, in <module>
    from detectron.ops.collect_and_distribute_fpn_rpn_proposals \
  File "/densepose/detectron/ops/collect_and_distribute_fpn_rpn_proposals.py", line 19, in <module>
    import detectron.roi_data.fast_rcnn as fast_rcnn_roi_data
  File "/densepose/detectron/roi_data/fast_rcnn.py", line 26, in <module>
    import detectron.roi_data.body_uv_rcnn as body_uv_rcnn_roi_data
  File "/densepose/detectron/roi_data/body_uv_rcnn.py", line 32, in <module>
    DP = dp_utils.DensePoseMethods()
  File "/densepose/detectron/utils/densepose_methods.py", line 18, in __init__
    ALP_UV = loadmat( os.path.join(os.path.dirname(__file__), '../../DensePoseData/UV_data/UV_Processed.mat')  )
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 135, in loadmat
    MR = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 58, in mat_reader_factory
    byte_stream = _open_file(file_name, appendmat)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 23, in _open_file
    return open(file_like, 'rb')
IOError: [Errno 2] No such file or directory: '/densepose/detectron/utils/../../DensePoseData/UV_data/UV_Processed.mat'
` 

I just haven't done the setting up the coco dataset, is that the problem?

**Comment by john7002** [comment]
I think this is a normal behavior. As your are using docker, the script gets the docker filesystem, not your local filesystem. Have a look the path of the missing file: 

`'/densepose/detectron/utils/../../DensePoseData/UV_data/UV_Processed.mat' `

When you generated the docker image, UV_data was empty. A possible fix would be first to generate DenseposeData, delete your current docker image, edit the dockerfile and add this type of line for every missing files:

`COPY /your/filesystem/path/DensePoseData/UV_data/UV_Processed.mat /densepose/DensePoseData/UV_data/
`

Then re-generate your docker image. Hope it helps.

**Comment by vkhalidov** [comment]
@rachit2403 Yes, you need to setup all the data directories to be able to perform inference / training. You can check my suggestions in #24 where I mount all the necessary data directories into the docker container from the host.

**Comment by TianFuKang** [comment]
uv_data to UV_data.
OK
