### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by garimss** [facebookresearch/DensePose#244]
Why do I am keep getting this error?  I am not able to run infer_simple.py.

(pytorch) D:\git_hub\DensePose>python tools/infer_simple.py --cfg detectron2/$DETECTRON/configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml --output-dir /tmp/detectron-visualizations --image-ext jpg --wts model_final.pkl demo
Found Detectron ops lib: C:\Users\Garima\Anaconda3\envs\pytorch\lib\site-packages\torch/lib/caffe2_detectron_ops_gpu.dll
[E ..\caffe2\core\init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E ..\caffe2\core\init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E ..\caffe2\core\init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
WARNING cnn.py:  25: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
generalized_rcnn
<class 'bytes'> type of func_name
ERROR model_builder.py: 173: Failed to find function: b'generalized_rcnn'
Traceback (most recent call last):
  File "tools/infer_simple.py", line 141, in <module>
    main(args)
  File "tools/infer_simple.py", line 92, in main
    model = infer_engine.initialize_model_from_cfg(args.weights)
  File "d:\git_hub\densepose\detectron2\$detectron\detectron\core\test_engine.py", line 327, in initialize_model_from_cfg
    model = model_builder.create(cfg.MODEL.TYPE, train=False, gpu_id=gpu_id)
  File "d:\git_hub\densepose\detectron2\$detectron\detectron\modeling\model_builder.py", line 126, in create
    return get_func(model_type_func)(model)
  File "d:\git_hub\densepose\detectron2\$detectron\detectron\modeling\model_builder.py", line 148, in get_func
    parts = func_name.split('.')
TypeError: a bytes-like object is required, not 'str'

(pytorch) D:\git_hub\DensePose>

**Comment by garimss** [comment]
I am using this on pytorch installed through conda. python3.7 cuda 10.
