### ISSUE TITLE
[enforce fail at conv_op_cudnn.cc:555] filter.dim32(1) == C / group_. 8 vs 256 Error from operator:

### ISSUE THREAD

**Issue by AlexLuya** [facebookresearch/DensePose#31]
source git HEAD:bee2a8a96d3d6cfa9344c8dd341b25fba7ef5580
I build Densepose from source,when run:
`python2 tools/infer_simple.py --cfg configs/DensePose_ResNet101_FPN_s1x-e2e.yaml    --output-dir DensePoseData/infer_out/    --image-ext jpg   --wts /path/to/file/DensePose_ResNet101_FPN_32x8d_s1x-e2e.pkl DensePoseData/demo_data/demo_im.jpg`

get error:
```
I0625 17:30:15.627099   563 net_async_base.cc:421] Using specified CPU pool size: 4; NUMA node id: -1
I0625 17:30:15.627120   563 net_async_base.cc:426] Created new CPU pool, size: 4; NUMA node id: -1
E0625 17:30:16.176945   627 net_async_base.cc:349] [enforce fail at conv_op_cudnn.cc:555] filter.dim32(1) == C / group_. 8 vs 256 Error from operator: 
input: "gpu_0/res2_0_branch2a" input: "gpu_0/res2_0_branch2b_w" output: "gpu_0/res2_0_branch2b" name: "" type: "Conv" arg { name: "kernel" i: 3 } arg { name: "exhaustive_search" i: 0 } arg { name: "stride" i: 1 } arg { name: "pad" i: 1 } arg { name: "order" s: "NCHW" } arg { name: "dilation" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN",  op Conv
WARNING workspace.py: 185: Original python traceback for operator `7` in network `generalized_rcnn` in exception above (most recent call last):
```

```
WARNING workspace.py: 190:   File "/usr/local/lib/python2.7/dist-packages/caffe2/python/helpers/conv.py", line 139, in _ConvBase
Traceback (most recent call last):
  File "tools/infer_simple.py", line 140, in <module>
    main(args)
  File "tools/infer_simple.py", line 109, in main
    model, im, None, timers=timers
  File "/home/alex/DensePose/detectron/core/test.py", line 58, in im_detect_all
    model, im, cfg.TEST.SCALE, cfg.TEST.MAX_SIZE, boxes=box_proposals
  File "/home/alex/DensePose/detectron/core/test.py", line 158, in im_detect_bbox
    workspace.RunNet(model.net.Proto().name)
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 217, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 178, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at conv_op_cudnn.cc:555] filter.dim32(1) == C / group_. 8 vs 256 Error from operator: 
input: "gpu_0/res2_0_branch2a" input: "gpu_0/res2_0_branch2b_w" output: "gpu_0/res2_0_branch2b" name: "" type: "Conv" arg { name: "kernel" i: 3 } arg { name: "exhaustive_search" i: 0 } arg { name: "stride" i: 1 } arg { name: "pad" i: 1 } arg { name: "order" s: "NCHW" } arg { name: "dilation" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"

```

how to solve this problem?

**Comment by vkhalidov** [comment]
Could you please specify your CUDA and CUDNN versions and how did you install Caffe2?

**Comment by AlexLuya** [comment]
@vkhalidov 
CUDA: 9.0.176
CUDNN:7.14
OS:ubuntu 16.04 64bit

and I installed caffe2 from source by 
`make &sudo make install`
**not** by 
`python setup.py install`
 due to
` CUDA_NVCC_EXECUTABLE `
not found even 
`echo $CUDA_NVCC_EXECUTABLE `
will print out 
`/usr/local/cuda/bin/nvcc`

**Comment by vkhalidov** [comment]
OK, thanks for the details. Could you please also specify the commit hash of Caffe2?

**Comment by AlexLuya** [comment]
@vkhalidov 
caffe2's commit hash is e31ab999320076b179b9d99917873cbf9612b6ed

**Comment by AlexLuya** [comment]
@vkhalidov 
my mistake:
`DensePose_ResNet101_FPN_s1x-e2e.yaml  vs DensePose_ResNet101_FPN_32x8d_s1x-e2e.pkl `
cfg **### not match** pkl

**Comment by liu-xb** [comment]
I have the same error. So you replace DensePose_ResNet101_FPN_32x8d_s1x-e2e.pkl with DensePose_ResNet101_FPN_s1x-e2e.yaml and get it work? @AlexLuya  Thank you very much

**Comment by liu-xb** [comment]
Oh. I know what is wrong. My mistake. Thank you @AlexLuya
