### ISSUE TITLE
Minimum GPU requirements for Testing/Inference?

### ISSUE THREAD

**Issue by samhains** [facebookresearch/DensePose#38]
Attempted to get this running on a GeForce GTX 760 with 3gbs ram, and... (perhaps unsurprisingly)  i'm getting an 'out of memory' error trying to run the simple inference example... 

Does anyone know what the minimum memory required might be to test this model?

**Comment by phraust1612** [comment]
Same here,
An error occurred during loading DenseReg GT, after the test ended.
I used google cloud platform of 2 cpu with 8GB memories, and Tesla P100 for gpu.
The error message was like blow

> Loading densereg GT..
/home/byeonguk/densepose/detectron/datasets/../../DensePoseData/eval_data/
Traceback (most recent call last):
  File "tools/test_net.py", line 111, in <module>
    check_expected_results=True,
  File "/home/byeonguk/densepose/detectron/core/test_engine.py", line 120, in run_inference
    all_results = result_getter()
  File "/home/byeonguk/densepose/detectron/core/test_engine.py", line 100, in result_getter
    multi_gpu=multi_gpu_testing
  File "/home/byeonguk/densepose/detectron/core/test_engine.py", line 158, in test_net_on_dataset
    dataset, all_boxes, all_segms, all_keyps, all_bodys, output_dir
  File "/home/byeonguk/densepose/detectron/datasets/task_evaluation.py", line 65, in evaluate_all
    results = evaluate_body_uv(dataset, all_boxes, all_bodys, output_dir)
  File "/home/byeonguk/densepose/detectron/datasets/task_evaluation.py", line 159, in evaluate_body_uv
    cleanup=not_comp
  File "/home/byeonguk/densepose/detectron/datasets/json_dataset_evaluator.py", line 449, in evaluate_body_uv
    coco_eval = _do_body_uv_eval(json_dataset, results, output_dir)
  File "/home/byeonguk/densepose/detectron/datasets/json_dataset_evaluator.py", line 543, in _do_body_uv_eval
    coco_eval.evaluate()
  File "/home/byeonguk/densepose/detectron/datasets/densepose_cocoeval.py", line 191, in evaluate
    self._prepare()
  File "/home/byeonguk/densepose/detectron/datasets/densepose_cocoeval.py", line 148, in _prepare
    self._loadGEval()
  File "/home/byeonguk/densepose/detectron/datasets/densepose_cocoeval.py", line 123, in _loadGEval
    arrays[k] = np.array(v)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/dataset.py", line 690, in __array__
    arr = numpy.empty(self.shape, dtype=self.dtype if dtype is None else dtype)
MemoryError

**Comment by fire17** [comment]
Also interested in System Requirements

Assuming that the requirements are different for Training and for Running trained models,
what are the Minimum System Requirements for each?

also since im here, anyone knows how to get to a trained model that works with a webcam? could not find it.

Thanks a lot!!!

**Comment by Tetsujinfr** [comment]
Me too, can not get it to work on a 980ti: is Maxell GPUs not supported/tested?

**Comment by ingramator** [comment]
Any answer to this? Certainly the Resnet101 models won't work under 4GB of GRAM

**Comment by Tetsujinfr** [comment]
I could not see anyone yet who managed to infer this code unless using the docker image. Happy to be proven wrong but when you google on the net you find always the same videos/images, except a few docker user people. Hopefully missing something here but I never spent so much time failing to install a githib project, and I did struggle with quite a few ones. Possibly the difficulty here is more about caffe2 than Denspose tbh.

**Comment by Tetsujinfr** [comment]
I finally got it to work fine with my 980ti (cuda8.0 cudnn7, ubuntu 16.04 re-installed everything from scratch, painful but did work in yhe end). So eventually it works fine on Maxwell.

**Comment by ingramator** [comment]
If you have a GTX 970 or any card with around 4GB RAM you can comfortably run inference with the ResNet50 architecture
