### ISSUE TITLE
How to train model with keypoint detection support? 

### ISSUE THREAD

**Issue by AlexLuya** [facebookresearch/DensePose#39]
Hello,
     I have added 
          ` KEYPOINTS_ON: True`
to 
          ` DensePose_ResNet101_FPN_32x8d_s1x-e2e.yaml`
```
MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet101_conv5_body
  NUM_CLASSES: 2
  FASTER_RCNN: True
  BODY_UV_ON: True
  KEYPOINTS_ON: True
```
and start training,but got error like this:
 ```
       'RPN_PRE_NMS_TOP_N': 2000,
           'RPN_STRADDLE_THRESH': 0,
           'SCALES': (640, 672, 704, 736, 768, 800),
           'SNAPSHOT_ITERS': 20000,
           'USE_FLIPPED': True,
           'WEIGHTS': '/home/alex/models/densepose/X-101-32x8d.pkl'},
 'USE_NCCL': False,
 'VIS': False,
 'VIS_TH': 0.9}
INFO train.py: 123: Building model: generalized_rcnn
WARNING cnn.py:  25: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
Traceback (most recent call last):
  File "tools/train_net.py", line 119, in <module>
    main()
  File "tools/train_net.py", line 101, in main
    checkpoints = detectron.utils.train.train_model()
  File "/home/alex/DensePose/detectron/utils/train.py", line 45, in train_model
    model, weights_file, start_iter, checkpoints, output_dir = create_model()
  File "/home/alex/DensePose/detectron/utils/train.py", line 124, in create_model
    model = model_builder.create(cfg.MODEL.TYPE, train=True)
  File "/home/alex/DensePose/detectron/modeling/model_builder.py", line 119, in create
    return get_func(model_type_func)(model)
  File "/home/alex/DensePose/detectron/modeling/model_builder.py", line 84, in generalized_rcnn
    freeze_conv_body=cfg.TRAIN.FREEZE_CONV_BODY
  File "/home/alex/DensePose/detectron/modeling/model_builder.py", line 233, in build_generic_detection_model
    optim.build_data_parallel_model(model, _single_gpu_build_func)
  File "/home/alex/DensePose/detectron/modeling/optimizer.py", line 32, in build_data_parallel_model
    all_loss_gradients = _build_forward_graph(model, single_gpu_build_func)
  File "/home/alex/DensePose/detectron/modeling/optimizer.py", line 55, in _build_forward_graph
    all_loss_gradients.update(single_gpu_build_func(model))
  File "/home/alex/DensePose/detectron/modeling/model_builder.py", line 214, in _single_gpu_build_func
    spatial_scale_conv
  File "/home/alex/DensePose/detectron/modeling/model_builder.py", line 306, in _add_roi_keypoint_head
    model, blob_in, dim_in, spatial_scale_in
TypeError: 'NoneType' object is not callable
```

What does this mean?

**Comment by vkhalidov** [comment]
It looks like you haven't specified the keypoints head in the model. Please check an example config file from [Detectron](https://github.com/facebookresearch/Detectron/blob/master/configs/12_2017_baselines/e2e_keypoint_rcnn_R-101-FPN_s1x.yaml). In particular

```
KRCNN:
  ROI_KEYPOINTS_HEAD: keypoint_rcnn_heads.add_roi_pose_head_v1convX
  NUM_STACKED_CONVS: 8
  NUM_KEYPOINTS: 17
  USE_DECONV_OUTPUT: True
  CONV_INIT: MSRAFill
  CONV_HEAD_DIM: 512
  UP_SCALE: 2
  HEATMAP_SIZE: 56  # ROI_XFORM_RESOLUTION (14) * UP_SCALE (2) * USE_DECONV_OUTPUT (2)
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14
  ROI_XFORM_SAMPLING_RATIO: 2
  KEYPOINT_CONFIDENCE: bbox
```
