### ISSUE TITLE
Disabling region proposal network

### ISSUE THREAD

**Issue by Ali2500** [facebookresearch/DensePose#41]
I would like to use my own region proposals instead of the RPN used by the model. I tried to directly call detectron.core.test.im_detect_body_uv directly with my own bounding box proposals, but I get a cryptic error when the code reaches this line: 'workspace.RunNet(model.body_uv_net.Proto().name)':

> Traceback (most recent call last):
  File "/usr/home/athar/work/framework/preprocessing/generate_dense_poses.py", line 228, in <module>
    main(parser.parse_args())
  File "/usr/home/athar/work/framework/preprocessing/generate_dense_poses.py", line 213, in main
    dense_pose_generator.process_dataset(dataset_path, args.min_detection_score)
  File "/usr/home/athar/work/framework/preprocessing/generate_dense_poses.py", line 177, in process_dataset
    iuv_mask, person_id_mask = self.detect_in_frame(frame_num)
  File "/usr/home/athar/work/framework/preprocessing/generate_dense_poses.py", line 95, in detect_in_frame
    iuv, inds = self.inference_engine.detect_uv_pose_from_bboxes(image, boxes, 0.694270833333)
  File "/usr/home/athar/work/framework/preprocessing/detectron_inference.py", line 60, in detect_uv_pose_from_bboxes
    cls_bodys = infer_engine.im_detect_body_uv(self.model, im_scale, boxes)
  File "/data2/ali-working-dir/dense-pose-api/detectron/core/test.py", line 911, in im_detect_body_uv
    workspace.RunNet(model.body_uv_net.Proto().name)
  File "/data2/ali-working-dir/pytorch-deployed/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 217, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/data2/ali-working-dir/pytorch-deployed/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 178, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at blob.h:84] IsType<T>(). wrong type for the Blob instance. Blob contains nullptr (uninitialized) while caller expects caffe2::Tensor<caffe2::CUDAContext> .
Offending Blob name: gpu_0/fpn_res4_22_sum.
Error from operator: 
input: "gpu_0/fpn_res4_22_sum" input: "gpu_0/body_uv_rois_fpn4" output: "gpu_0/_[body_uv]_roi_feat_fpn4" name: "" type: "RoIAlign" arg { name: "pooled_h" i: 14 } arg { name: "sampling_ratio" i: 2 } arg { name: "spatial_scale" f: 0.0625 } arg { name: "pooled_w" i: 14 } device_option { device_type: 1 cuda_gpu_id: 0 }

I am assuming I'll have to modify the config file in some way to get this working, but I'm not sure. Any help?

**Comment by vkhalidov** [comment]
@Ali2500 could you please precise which config you are using?

**Comment by Ali2500** [comment]
The default config provided. The only change is that I have increased 'DETECTIONS_PER_IM' to 100. Interestingly, if I call im_detect_all() and just replace the 'boxes' and 'cls_boxes' that it computes with my own, everything works fine. Is the call to im_detect_body_uv() somehow dependent on the previous calls to get the bounding boxes?
