### ISSUE TITLE
KeyError: u'rois'

### ISSUE THREAD

**Issue by nowgood** [facebookresearch/DensePose#45]
Notice, this error only happened when I use small model `DensePose_ResNet50_FPN_s1x.yaml`,  other model like `DensePose_ResNet101_FPN_s1x-e2e.pkl`, `DensePose_ResNet101_FPN_32x8d_s1x-e2e.yaml` is fine.

when I ran script 
```
python tools/infer_simple.py \
    --cfg configs/DensePose_ResNet50_FPN_s1x.yaml \
    --output-dir /home/wangbin/Desktop/densepose/star_small_model \
    --image-ext jpg \
    --wts /home/wangbin/models/densepose/DensePose_ResNet50_FPN_s1x.pkl \
    /home/wangbin/Downloads/imageAssist/star
```
errors happens as follow:
```
INFO infer_simple.py: 103: Processing /home/wangbin/Downloads/imageAssist/star/ia_10008.jpg -> /home/wangbin/Desktop/densepose/star_small_model/ia_10008.jpg.pdf
Traceback (most recent call last):
  File "tools/infer_simple.py", line 140, in <module>
    main(args)
  File "tools/infer_simple.py", line 109, in main
    model, im, None, timers=timers
  File "/home/wangbin/github/densepose/detectron/core/test.py", line 58, in im_detect_all
    model, im, cfg.TEST.SCALE, cfg.TEST.MAX_SIZE, boxes=box_proposals
  File "/home/wangbin/github/densepose/detectron/core/test.py", line 145, in im_detect_bbox
    hashes = np.round(inputs['rois'] * cfg.DEDUP_BOXES).dot(v)
KeyError: u'rois'

```
os: ubuntu16.04
g++: 5.4
cuda8.0+cudnn7.0.5
caffe2 master branch newly complied

**Comment by vkhalidov** [comment]
@nowgood this is normal behavior, since end-to-end models (e2e) generate region proposals; for other models you need to provide them to the `im_detect_all` method
