### ISSUE TITLE
question about the installation of Detectron

### ISSUE THREAD

**Issue by zy2008cn** [facebookresearch/DensePose#57]
Check that Detectron tests pass (e.g. for [`SpatialNarrowAsOp test`](tests/test_spatial_narrow_as_op.py)):

Error:
No handlers could be found for logger "caffe2.python.net_drawer"
net_drawer will not run correctly. Please install the correct dependencies.
E0706 14:35:10.201040 28778 init_intrinsics_check.cc:59] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0706 14:35:10.201071 28778 init_intrinsics_check.cc:59] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0706 14:35:10.201086 28778 init_intrinsics_check.cc:59] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Found Detectron ops lib: /usr/local/lib/libcaffe2_detectron_ops_gpu.so
Traceback (most recent call last):
  File "/home/imi/MASKRCNN/densepose/detectron/tests/test_spatial_narrow_as_op.py", line 80, in <module>
    c2_utils.import_detectron_ops()
  File "/home/imi/MASKRCNN/densepose/detectron/utils/c2.py", line 34, in import_detectron_ops
    dyndep.InitOpsLibrary(detectron_ops_lib)
  File "/home/imi/Documents/caffe2/build/caffe2/python/dyndep.py", line 50, in InitOpsLibrary
    _init_impl(name)
  File "/home/imi/Documents/caffe2/build/caffe2/python/dyndep.py", line 63, in _init_impl
    ctypes.CDLL(path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/libcaffe2_detectron_ops_gpu.so: undefined symbol: _ZN6caffe231_DeviceOption_default_instance_E

don't know why ,while other operations are OK.

**Comment by javierfuenca** [comment]
Did you run make ops?

**Comment by vkhalidov** [comment]
You need to check links (see `ldd`) and symbols (see `nm`), this error might happen when you've got several versions of Caffe2 installed on your system.
