### ISSUE TITLE
Numpy issue while trying to install/run densepose

### ISSUE THREAD

**Issue by gamenn** [facebookresearch/DensePose#69]
I have been trying for three days to get densepose running on my machine, which has Ubuntu 16.04. 

I built caffe2 from source. The tests for it ran fine.
After that I tried to run "python2 tools/infer_simple.py ....." to process an image. That gave me an error about cv2 module missing. Based on internet searches about that, I installed some OpenCV packages.
Now. I am getting the following error:

```
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named caffe2_pybind11_state_hip
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
Traceback (most recent call last):
  File "tools/infer_simple.py", line 34, in <module>
    import detectron.core.test_engine as infer_engine
  File "/home/ANT.AMAZON.COM/venajj/Installs/densepose/detectron/core/test_engine.py", line 27, in <module>
    from detectron.core.rpn_generator import generate_rpn_on_dataset
  File "/home/ANT.AMAZON.COM/venajj/Installs/densepose/detectron/core/rpn_generator.py", line 34, in <module>
    from detectron.datasets import task_evaluation
  File "/home/ANT.AMAZON.COM/venajj/Installs/densepose/detectron/datasets/task_evaluation.py", line 37, in <module>
    import detectron.datasets.cityscapes_json_dataset_evaluator \
  File "/home/ANT.AMAZON.COM/venajj/Installs/densepose/detectron/datasets/cityscapes_json_dataset_evaluator.py", line 20, in <module>
    import pycocotools.mask as mask_util
  File "build/bdist.linux-x86_64/egg/pycocotools/mask.py", line 3, in <module>
  File "build/bdist.linux-x86_64/egg/pycocotools/_mask.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/pycocotools/_mask.py", line 6, in __bootstrap__
  File "pycocotools/_mask.pyx", line 23, in init pycocotools._mask
  File "__init__.pxd", line 1000, in numpy.import_array
ImportError: numpy.core.multiarray failed to import
```

Any idea how to fix this? 
Thanks.

**Comment by vkhalidov** [comment]
Looks like COCO API uses wrong NumPy. You should check your COCO API installation.
