### ISSUE TITLE
make install fails for COCOAPI

### ISSUE THREAD

**Issue by gamenn** [facebookresearch/DensePose#72]
Under the instructions for installing COCOAPI, one of the steps is to run "make install". When I do that, I get the following error:

```
# install pycocotools to the Python site-packages
python setup.py build_ext install
running build_ext
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
running install
Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    ext_modules= ext_modules
  File "/myHomeDirectory/anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/myHomeDirectory/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/myHomeDirectory/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 103, in do_egg_install
    cmd.ensure_finalized()  # finalize before bdist_egg munges install cmd
  File "/myHomeDirectory/anaconda2/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 289, in finalize_options
    'install_lib', ('install_dir', 'install_dir')
  File "/myHomeDirectory/anaconda2/lib/python2.7/distutils/cmd.py", line 298, in set_undefined_options
    src_cmd_obj.ensure_finalized()
  File "/myHomeDirectory/anaconda2/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install_lib.py", line 17, in finalize_options
    self.set_undefined_options('install',('install_layout','install_layout'))
  File "/myHomeDirectory/anaconda2/lib/python2.7/distutils/cmd.py", line 302, in set_undefined_options
    getattr(src_cmd_obj, src_option))
  File "/myHomeDirectory/anaconda2/lib/python2.7/distutils/cmd.py", line 105, in __getattr__
    raise AttributeError, attr
AttributeError: install_layout
Makefile:7: recipe for target 'install' failed
make: *** [install] Error 1
`````

How can I fix this issue? 
I am using Ubuntu 16.04.

**Comment by gamenn** [comment]
I was able to fix this by deleting some Python files present under the .local folder beneath my home directory.

**Comment by azzaBouleimen** [comment]
I'm having the same error, what are the files you had to delete please ?
