### ISSUE TITLE
patch_compatible. cuDNN compiled (7102) and runtime (7 005) versions mismatch

### ISSUE THREAD

**Issue by 008karan** [facebookresearch/DensePose#73]
I installed caffe2 with conda method with cuda-8 and cudnn 7. I am doing all this on google cloud ubunto 16.04. It passed tests:
```
`python2 -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"
To check if Caffe2 GPU build was successful
 This must print a number > 0 in order to use Detectron
python2 -c 'from caffe2.python import workspace; print(workspace.NumCudaDevices())
```
Then after cloning densepose its giving error in this line:
`python2 $DENSEPOSE/detectron/tests/test_spatial_narrow_as_op.py`

output:
**No handlers could be found for logger "caffe2.python.net_drawer"
net_drawer will not run correctly. Please install the correct dependencies
.
E0718 22:55:32.043427 22116 init_intrinsics_check.cc:43] CPU feature avx i
s present on your machine, but the Caffe2 binary is not compiled with it. 
It means you may not get the full speed of your CPU.
E0718 22:55:32.043540 22116 init_intrinsics_check.cc:43] CPU feature avx2 
is present on your machine, but the Caffe2 binary is not compiled with it.
 It means you may not get the full speed of your CPU.
E0718 22:55:32.043599 22116 init_intrinsics_check.cc:43] CPU feature fma i
s present on your machine, but the Caffe2 binary is not compiled with it. 
It means you may not get the full speed of your CPU.
Found Detectron ops lib: /home/g008kaaraan/anaconda2/envs/env1/lib/libcaff
e2_detectron_ops_gpu.so
E..
===================================================================
ERROR: test_large_forward (__main__.SpatialNarrowAsOpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_spatial_narrow_as_op.py", line 60, in test_large_forward
    self._run_test(A, B)
  File "test_spatial_narrow_as_op.py", line 29, in _run_test
    workspace.FeedBlob('A', A)
  File "/home/g008kaaraan/anaconda2/envs/env1/lib/python2.7/site-packages/
caffe2/python/workspace.py", line 315, in FeedBlob
    return C.feed_blob(name, arr, StringifyProto(device_option))
RuntimeError: [enforce fail at common_cudnn.h:108] version_match || backwa
rds_compatible_7 || patch_compatible. cuDNN compiled (7102) and runtime (7
005) versions mismatch 
----------------------------------------------------------------------
**Ran 3 tests in 1.022s
FAILED (errors=1)**
I only installed one cudnn7 but why its giving me this error.

I also ran next line `cd $DENSEPOSE && make ops`
got this error:
**mkdir -p build && cd build && cmake .. && make -j1
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Caffe2: Found gflags with new-style gflags target.
-- Caffe2: Cannot find glog automatically. Using legacy find.
-- Could NOT find glog (missing: GLOG_INCLUDE_DIR GLOG_LIBRARY) 
CMake Warning at /home/g008kaaraan/anaconda2/envs/env1/share/cmake/Caffe2/
public/glog.cmake:66 (message):
  Caffe2: glog cannot be found.  Depending on whether you are building Caf
fe2
  or a Caffe2 dependent library, the next warning / error will give you mo
re
  info.
Call Stack (most recent call first):
  /home/g008kaaraan/anaconda2/envs/env1/share/cmake/Caffe2/Caffe2Config.cm
ake:36 (include)
  CMakeLists.txt:8 (find_package)
CMake Error at /home/g008kaaraan/anaconda2/envs/env1/share/cmake/Caffe2/Ca
ffe2Config.cmake:38 (message):
  Your installed Caffe2 version uses glog but the glog library cannot be
  found.  Did you accidentally remove it, or have you set the right
  CMAKE_PREFIX_PATH and/or GFLAGS_ROOT_DIR? If you do not have glog, you w
ill
  need to install glog and set the library path accordingly.
Call Stack (most recent call first):
  CMakeLists.txt:8 (find_package)
-- Configuring incomplete, errors occurred!
See also "/home/g008kaaraan/densepose/build/CMakeFiles/CMakeOutput.log".
See also "/home/g008kaaraan/densepose/build/CMakeFiles/CMakeError.log".
Makefile:13: recipe for target 'ops' failed
make: *** [ops] Error 1**

##    My bashrc file :
**export PATH=/usr/local/cuda-8.0/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64${LD_LIBRARY_PATH:+:${LD_L
IBRARY_PATH}}
export COCOAPI="/home/g008kaaraan/cocoapi"**

**Comment by vkhalidov** [comment]
This is related to the following [Detectron issue](https://github.com/facebookresearch/Detectron/issues/139). My advice would be to install Caffe2 from source instead of using precompiled binaries to avoid versions mismatch
