### ISSUE TITLE
undefined symbol: PyFPE_jbuf

### ISSUE THREAD

**Issue by lz199144** [facebookresearch/DensePose#8]
After successful installation, I run this commad.
`
python2 tools/infer_simple.py \
    --cfg configs/DensePose_ResNet101_FPN_s1x-e2e.yaml \
    --output-dir DensePoseData/infer_out/ \
    --image-ext jpg \
    --wts https://s3.amazonaws.com/densepose/DensePose_ResNet101_FPN_s1x-e2e.pkl \
    DensePoseData/demo_data/demo_im.jpg
`

And error occurs as bellow:
`
Traceback (most recent call last):
  File "tools/infer_simple.py", line 34, in <module>
    import detectron.core.test_engine as infer_engine
  File "/home/ricardoliu/Source/DensePose/detectron/core/test_engine.py", line 27, in <module>
    from detectron.core.rpn_generator import generate_rpn_on_dataset
  File "/home/ricardoliu/Source/DensePose/detectron/core/rpn_generator.py", line 34, in <module>
    from detectron.datasets import task_evaluation
  File "/home/ricardoliu/Source/DensePose/detectron/datasets/task_evaluation.py", line 37, in <module>
    import detectron.datasets.cityscapes_json_dataset_evaluator \
  File "/home/ricardoliu/Source/DensePose/detectron/datasets/cityscapes_json_dataset_evaluator.py", line 20, in <module>
    import pycocotools.mask as mask_util
  File "build/bdist.linux-x86_64/egg/pycocotools/mask.py", line 3, in <module>
  File "build/bdist.linux-x86_64/egg/pycocotools/_mask.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/pycocotools/_mask.py", line 6, in __bootstrap__
ImportError: /home/ricardoliu/.cache/Python-Eggs/pycocotools-2.0-py2.7-linux-x86_64.egg-tmp/pycocotools/_mask.so: undefined symbol: PyFPE_jbuf
`

**Comment by vkhalidov** [comment]
Do you happen to have [this](https://stackoverflow.com/questions/36190757/numpy-undefined-symbol-pyfpe-jbuf) kind of problem? It is difficult to suggest anything without the details on your configuration.
