### ISSUE TITLE
Simple infer EOF error in pickle.load()

### ISSUE THREAD

**Issue by jaskarannagi19** [facebookresearch/DensePose#88]
(Pose) jaskaran@jaskaran-pc:~/densepose$ python2 tools/infer_simple.py     --cfg configs/DensePose_ResNet101_FPN_s1x-e2e.yaml     --output-dir DensePoseData/infer_out/     --image-ext jpg     --wts https://s3.amazonaws.com/densepose/DensePose_ResNet101_FPN_s1x-e2e.pkl     DensePoseData/demo_data/demo_im2.jpg
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/h5py/__init__.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._conv import register_converters as _register_converters
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/h5py/__init__.py:45: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/h5py/_hl/group.py:22: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .. import h5g, h5i, h5o, h5r, h5t, h5l, h5p
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/linalg/basic.py:17: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._solve_toeplitz import levinson
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/linalg/__init__.py:207: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._decomp_update import *
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/special/__init__.py:640: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ufuncs import *
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/special/_ellip_harm.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/interpolate/_bsplines.py:10: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _bspl
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/sparse/lil.py:19: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _csparsetools
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:165: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._shortest_path import shortest_path, floyd_warshall, dijkstra,\
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/sparse/csgraph/_validation.py:5: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._tools import csgraph_to_dense, csgraph_from_dense,\
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:167: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._traversal import breadth_first_order, depth_first_order, \
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:169: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._min_spanning_tree import minimum_spanning_tree
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:170: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._reordering import reverse_cuthill_mckee, maximum_bipartite_matching, \
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/spatial/__init__.py:95: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .ckdtree import *
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/spatial/__init__.py:96: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .qhull import *
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/spatial/_spherical_voronoi.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _voronoi
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/spatial/distance.py:122: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _hausdorff
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/io/matlab/mio4.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .mio_utils import squeeze_element, chars_to_strings
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/io/matlab/mio5.py:98: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .mio5_utils import VarReader5
Found Detectron ops lib: /home/jaskaran/.conda/envs/Pose/lib/libcaffe2_detectron_ops_gpu.so
E0802 23:45:53.853937  7429 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0802 23:45:53.853955  7429 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0802 23:45:53.853958  7429 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
WARNING cnn.py:  25: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
INFO net.py:  51: Loading weights from: /tmp/detectron-download-cache/DensePose_ResNet101_FPN_s1x-e2e.pkl
Traceback (most recent call last):
  File "tools/infer_simple.py", line 140, in <module>
    main(args)
  File "tools/infer_simple.py", line 91, in main
    model = infer_engine.initialize_model_from_cfg(args.weights)
  File "/home/jaskaran/densepose/detectron/core/test_engine.py", line 336, in initialize_model_from_cfg
    model, weights_file, gpu_id=gpu_id,
  File "/home/jaskaran/densepose/detectron/utils/net.py", line 54, in initialize_gpu_from_weights_file
    src_blobs = pickle.load(f)
EOFError
(Pose) jaskaran@jaskaran-pc:~/densepose$ python2 tools/infer_simple.py     --cfg configs/DensePose_ResNet101_FPN_s1x-e2e.yaml     --output-dir DensePoseData/infer_out/     --image-ext jpg     --wts https://s3.amazonaws.com/densepose/DensePose_ResNet101_FPN_s1x-e2e.pkl     DensePoseData/demo_data/demo_im2.jpg
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/h5py/__init__.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._conv import register_converters as _register_converters
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/h5py/__init__.py:45: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/h5py/_hl/group.py:22: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .. import h5g, h5i, h5o, h5r, h5t, h5l, h5p
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/linalg/basic.py:17: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._solve_toeplitz import levinson
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/linalg/__init__.py:207: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._decomp_update import *
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/special/__init__.py:640: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ufuncs import *
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/special/_ellip_harm.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/interpolate/_bsplines.py:10: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _bspl
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/sparse/lil.py:19: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _csparsetools
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:165: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._shortest_path import shortest_path, floyd_warshall, dijkstra,\
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/sparse/csgraph/_validation.py:5: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._tools import csgraph_to_dense, csgraph_from_dense,\
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:167: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._traversal import breadth_first_order, depth_first_order, \
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:169: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._min_spanning_tree import minimum_spanning_tree
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:170: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._reordering import reverse_cuthill_mckee, maximum_bipartite_matching, \
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/spatial/__init__.py:95: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .ckdtree import *
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/spatial/__init__.py:96: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .qhull import *
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/spatial/_spherical_voronoi.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _voronoi
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/spatial/distance.py:122: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _hausdorff
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/io/matlab/mio4.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .mio_utils import squeeze_element, chars_to_strings
/home/jaskaran/.conda/envs/Pose/lib/python2.7/site-packages/scipy/io/matlab/mio5.py:98: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .mio5_utils import VarReader5
Found Detectron ops lib: /home/jaskaran/.conda/envs/Pose/lib/libcaffe2_detectron_ops_gpu.so
E0802 23:49:40.743532  7536 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0802 23:49:40.743549  7536 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0802 23:49:40.743552  7536 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
WARNING cnn.py:  25: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
INFO net.py:  51: Loading weights from: /tmp/detectron-download-cache/DensePose_ResNet101_FPN_s1x-e2e.pkl
Traceback (most recent call last):
  File "tools/infer_simple.py", line 140, in <module>
    main(args)
  File "tools/infer_simple.py", line 91, in main
    model = infer_engine.initialize_model_from_cfg(args.weights)
  File "/home/jaskaran/densepose/detectron/core/test_engine.py", line 336, in initialize_model_from_cfg
    model, weights_file, gpu_id=gpu_id,
  File "/home/jaskaran/densepose/detectron/utils/net.py", line 54, in initialize_gpu_from_weights_file
    src_blobs = pickle.load(f)
EOFError

Someone please help out sorry for being stupid I am a newbie to AI and linux as well

**Comment by peethamber** [comment]
This looks like you are running out of GPU memory on your system. What is your config of the system

**Comment by peethamber** [comment]
I have run the densepose simple infer python code on a similar conifg. Nvidia GTX 1050 4gb GPU. The only diff here i can see is that my system runs on 16GB RAM. This may not be  a problem and would rather be an evironment setup issue. Shall come back to you if something strikes.

**Comment by jaskarannagi19** [comment]
Environment setup passes all tests I am using anaconda method to setting up
environment ok for now I have paused it

**Comment by peethamber** [comment]
Try running the whole things with DensePose_ResNet50_FPN_s1x.pkl and DensePose_ResNet50_FPN_s1x.yaml. This model requires less mem when compared to Resnet101(less than 4GB). It could work. Nothing changes in the command line except the model and config file you use. I did the same thing when resnet101 ran out of mem.

**Comment by Madara321** [comment]
check the file DensePose_ResNet101_FPN_s1x-e2e.pkl

**Comment by ingramator** [comment]
Please see my comment on #38 which states that minimum GPU GDDR5 memory is 5GB for the basic resnet101. The architecture takes up too much RAM for standard <=4GB memory models

**Comment by jaskarannagi19** [comment]
I believe it was GPU memory issue some processes where using my GPU only 3 GB was available for use

**Comment by pavithraezhil** [comment]
Hello,
I am unable to run the model even after using ResNet50 weights.

------------------------------------ 
python2 tools/infer_simple.py \
>     --cfg configs/DensePose_ResNet50_FPN_s1x-e2e.yaml \
>     --output-dir DensePoseData/infer_out/ \
>     --image-ext jpg \
>     --wts DensePose_ResNet50_FPN_s1x-e2e.pkl \
>     DensePoseData/demo_data/demo_im.jpg
Found Detectron ops lib: /usr/local/lib/libcaffe2_detectron_ops_gpu.so
WARNING cnn.py:  25: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
INFO net.py:  51: Loading weights from: DensePose_ResNet50_FPN_s1x-e2e.pkl
[I net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 3.1928e-05 secs
[I net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 2.2677e-05 secs
[I net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 5.047e-06 secs
INFO infer_simple.py: 103: Processing DensePoseData/demo_data/demo_im.jpg -> DensePoseData/infer_out/demo_im.jpg.pdf
[I net_async_base.h:212] Using specified CPU pool size: 4; device id: -1
[I net_async_base.h:217] Created new CPU pool, size: 4; device id: -1
Killed
-------------------------------------------------

System Config:
Ubuntu 16.04, CUDA 10
OpenCV 3.4.4, Caffe2 from source with GPU support
GPU: 2080Ti, 11GB memory
I am using python2.7 via virtualenv

Please help. Thank you.
