### ISSUE TITLE
Multithreading DensePose

### ISSUE THREAD

**Issue by minthetkhine** [facebookresearch/DensePose#93]
I would like to use DensePose on real-time camera input from ROS and to prevent loss of information from a sequential pipeline, I tried a multithreading approach. Because DensePose takes relatively quite some time to run compared to the input rate from the camera, DensePose only starts after about 4 or 5 images. So, I am using a queue to store all the images and 3-4 threads to run simultaneously on each consecutive image in its own thread. But when I run this, I get something like this

```
E0808 15:45:11.653666 61082 net_async_scheduling.cc:213] Detected concurrent runs
E0808 15:45:11.653697 61082 net.h:57] Failed to execute async run
thread2 failed
```

May I know why I get these errors?

**Comment by minthetkhine** [comment]
```
E0809 13:54:40.390210 101295 net_async_scheduling.cc:213] Detected concurrent runs
E0809 13:54:40.390240 101295 net.h:57] Failed to execute async run
Exception in thread thread2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/alfred/catkin_ws/src/live_pytorch/src/segmenter.py", line 119, in worker
    densepose(data)
  File "/home/alfred/catkin_ws/src/live_pytorch/src/segmenter.py", line 77, in densepose
    cls_boxes, cls_segms, cls_keyps, cls_bodys = infer_engine.im_detect_all(model, cv_image, None, timers=timers)
  File "/home/alfred/exp/DensePose/detectron/core/test.py", line 58, in im_detect_all
    model, im, cfg.TEST.SCALE, cfg.TEST.MAX_SIZE, boxes=box_proposals
  File "/home/alfred/exp/DensePose/detectron/core/test.py", line 158, in im_detect_bbox
    workspace.RunNet(model.net.Proto().name)
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 219, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 180, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at pybind_state.cc:1111] success. Error running net generalized_rcnn 
```

Sorry I forgot to post this error message.

**Comment by vkhalidov** [comment]
I guess you've already got the answer in [PyTorch #10471](https://github.com/pytorch/pytorch/issues/10471)

**Comment by minthetkhine** [comment]
```
Exception in thread thread1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/alfred/catkin_ws/src/live_pytorch/src/segmenter.py", line 136, in worker
    assert_and_infer_cfg(cache_urls=False)
  File "/home/alfred/exp/DensePose/detectron/core/config.py", line 1115, in assert_and_infer_cfg
    __C.RPN.RPN_ON = True
  File "/home/alfred/exp/DensePose/detectron/utils/collections.py", line 41, in __setattr__
    format(name, value)
AttributeError: Attempted to set "RPN_ON" to "True", but AttrDict is immutable

Exception in thread thread0:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/alfred/catkin_ws/src/live_pytorch/src/segmenter.py", line 136, in worker
    assert_and_infer_cfg(cache_urls=False)
  File "/home/alfred/exp/DensePose/detectron/core/config.py", line 1115, in assert_and_infer_cfg
    __C.RPN.RPN_ON = True
  File "/home/alfred/exp/DensePose/detectron/utils/collections.py", line 41, in __setattr__
    format(name, value)
AttributeError: Attempted to set "RPN_ON" to "True", but AttrDict is immutable
```

I finally got to make separate copies of the same model to each thread thanks to the previous advice, but I now face this new error. I wonder if I am really creating copies of the same model or using the same model in-place. 

```
def worker(self, workspace):

        # model
        merge_cfg_from_file('/home/alfred/exp/DensePose/configs/DensePose_ResNet101_FPN_s1x-e2e.yaml')
        weights = cache_url('https://s3.amazonaws.com/densepose/DensePose_ResNet101_FPN_s1x-e2e.pkl', cfg.DOWNLOAD_CACHE)
        assert_and_infer_cfg(cache_urls=False)
        model = infer_engine.initialize_model_from_cfg(weights)

        while True:
            data = self.tasks.get()
            self.densepose(data, model)
```

I am initializing each model in the worker function like this. May I know where I went wrong? Thank you.

**Comment by chqiwang** [comment]
@minthetkhine You need pass make_immutable=False to assert_and_infer_cfg
